name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-${{ secrets.NIM }}:latest

    - name: Deploy to Kubernetes
      uses: indiesdev/curl@v1.1
      with:
        url: "http://154.26.139.201:8080/deploy"
        method: "POST"
        headers: '{ "accept": "*/*" }'
        params: '{ "nim": "${{ secrets.NIM }}", "nama": "${{ secrets.NAMA }}", "docker_username": "${{ secrets.DOCKER_USERNAME }}" }'
        log-response: true
        retries: 3
        timeout: 10000